name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    # install and run locally via e.g.:
    # brew install pre-commit shellcheck && pre-commit run -a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Packer
        uses: hashicorp-contrib/setup-packer@v3
        with:
          packer-version: 1.11.0
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23'
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
  golangci:
    # install and run locally via e.g.:
    # brew install golangci-lint && golangci-lint run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          args: --timeout=3m
